### ISSUE TITLE
Knowledge Base Not Populating Function Values When Supplying a Problem File

### ISSUE THREAD

**Issue by Archetype90** [KCL-Planning/ROSPlan#81]
ROSPlan Branch: devel
Ubuntu Version: 16.04 

When the initial world state is provided through a bash script (using service calls), function values
are properly stored and queryable in the knowledge base. For example, using the Turtlebot example and 
running the following service call gets us the following results (cut off to save space):

```
rosservice call /kcl_rosplan/get_current_knowledge "predicate_name: 'distance'" 
attributes: 
  - 
    knowledge_type: 2
    instance_type: ''
    instance_name: ''
    attribute_name: "distance"
    values: 
      - 
        key: "wp1"
        value: "wp0"
      - 
        key: "wp2"
        value: "wp0"
    function_value: 10.0
    is_negative: False

```

But, when that same initial world state is provided through a supplied problem file, the knowledge base
is not updated to reflect the functions or their values, as seen below. 

```
rosservice call /kcl_rosplan/get_current_knowledge "predicate_name: 'distance'" 
attributes: []

```
I would be happy to provide the domain, problem, and launch files if necessary, but they are slightly modified versions of the examples provided with this repository.
