### ISSUE TITLE
Querying Knowledge Base Operator Details Does Not Include Functions as Preconditions or Effects

### ISSUE THREAD

**Issue by Archetype90** [KCL-Planning/ROSPlan#84]
ROSPlan Branch: devel
Ubuntu Version: 16.04

When querying the KB to get operator_details for an action that uses a function as a precondition or effect, the function is not included in the operator details list of preconditions/effects.

As a result, there is no way to automatically check preconditions for functions in either the dispatcher. Therefore, the action will be dispatched to the component regardless of current state of the function. 

An example of this behavior can be seen below:

```
    (:durative-action recharge
        :parameters (?robot - robot)
        :duration (= ?duration 10)
        :condition (and
            (at start (<= (battery-level ?robot) 30)))
        :effect (and
            (at end (increase (battery-level ?robot) 100)))
    )
```

```
rosservice call /kcl_rosplan/get_domain_operator_details "name: 'recharge'" 
op: 
  formula: 
    name: "recharge"
    typed_parameters: 
      - 
        key: "robot"
        value: "robot"
  at_start_add_effects: []
  at_start_del_effects: []
  at_end_add_effects: []
  at_end_del_effects: []
  at_start_simple_condition: []
  over_all_simple_condition: []
  at_end_simple_condition: []
  at_start_neg_condition: []
  over_all_neg_condition: []
  at_end_neg_condition: []
```
